### ISSUE TITLE
speaker problem

### ISSUE THREAD

**Issue by littlecake** [TheMrBooyah/hassio-dirigera-client#3]
I have problem if the dirigera find speaker in the network.
Its possible to ignore this devices if they are not programmed ?

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun dirigera-client (no readiness notification)
s6-rc: info: service legacy-services successfully started
██████  ██ ██████  ██  ██████  ███████ ██████   █████       ██████ ██      ██ ███████ ███    ██ ████████
██   ██ ██ ██   ██ ██ ██       ██      ██   ██ ██   ██     ██      ██      ██ ██      ████   ██    ██
██   ██ ██ ██████  ██ ██   ███ █████   ██████  ███████     ██      ██      ██ █████   ██ ██  ██    ██
██   ██ ██ ██   ██ ██ ██    ██ ██      ██   ██ ██   ██     ██      ██      ██ ██      ██  ██ ██    ██
██████  ██ ██   ██ ██  ██████  ███████ ██   ██ ██   ██      ██████ ███████ ██ ███████ ██   ████    ██
2022-11-27 23:59:02.016  INFO 64 --- [           main] .d.i.d.c.m.DirigeraClientMqttApplication : Starting DirigeraClientMqttApplication v0.0.1-SNAPSHOT using Java 17.0.4 on ec803700-dirigera-client with PID 64 (/dirigera/dirigera-client-mqtt.jar started by root in /run/s6/legacy-services/dirigera-client)
2022-11-27 23:59:02.056 DEBUG 64 --- [           main] .d.i.d.c.m.DirigeraClientMqttApplication : Running with Spring Boot v2.7.5, Spring v5.3.23
2022-11-27 23:59:02.061  INFO 64 --- [           main] .d.i.d.c.m.DirigeraClientMqttApplication : No active profile set, falling back to 1 default profile: "default"
2022-11-27 23:59:07.447  INFO 64 --- [           main] d.d.i.d.client.api.http.TokenStore       : Load access token
2022-11-27 23:59:09.498  INFO 64 --- [           main] d.d.i.d.client.api.http.ClientOAuthApi   : Dirigera client name: ec803700-dirigera-client
2022-11-27 23:59:14.092 DEBUG 64 --- [           main] d.d.iot.dirigera.client.mqtt.MqttBridge  : Connect to MQTT broker: host=core-mosquitto, port=1883, publisherId=12fa5ddf-bf67-4445-87bf-6ceeedace5af_1, reconnect=true, timeout=10
2022-11-27 23:59:14.649  INFO 64 --- [           main] d.d.iot.dirigera.client.mqtt.MqttBridge  : Connection to MQTT broker successfully established
2022-11-27 23:59:17.325  INFO 64 --- [           main] .d.i.d.c.m.DirigeraClientMqttApplication : Started DirigeraClientMqttApplication in 19.264 seconds (JVM running for 21.884)
2022-11-27 23:59:17.345 DEBUG 64 --- [           main] d.d.iot.dirigera.client.mqtt.MqttBridge  : Register event handler LightEventHandler for device class LightDevice
2022-11-27 23:59:17.347 DEBUG 64 --- [           main] d.d.iot.dirigera.client.mqtt.MqttBridge  : Register event handler OutletEventHandler for device class OutletDevice
2022-11-27 23:59:17.347 DEBUG 64 --- [           main] d.d.iot.dirigera.client.mqtt.MqttBridge  : Register event handler MotionSensorEventHandler for device class MotionSensorDevice
2022-11-27 23:59:18.453 ERROR 64 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at de.dvdgeisler.iot.dirigera.client.mqtt.DirigeraClientMqttApplication.main(DirigeraClientMqttApplication.java:77) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[dirigera-client-mqtt.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[dirigera-client-mqtt.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[dirigera-client-mqtt.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[dirigera-client-mqtt.jar:0.0.1-SNAPSHOT]
Caused by: org.springframework.core.codec.DecodingException: JSON decoding error: Could not resolve type id 'speaker' as a subtype of `de.dvdgeisler.iot.dirigera.client.api.model.device.Device<java.lang.Object,java.lang.Object>`: known type ids = [Device, airPurifier, blinds, blindsController, gateway, light, lightController, motionSensor, outlet, repeater, shortcutController, soundController]; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'speaker' as a subtype of `de.dvdgeisler.iot.dirigera.client.api.model.device.Device<java.lang.Object,java.lang.Object>`: known type ids = [Device, airPurifier, blinds, blindsController, gateway, light, lightController, motionSensor, outlet, repeater, shortcutController, soundController]
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 2281] (through reference chain: java.util.ArrayList[2])
	at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:242) ~[spring-web-5.3.23.jar!/:5.3.23]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Body from GET https://192.168.100.27:8443/v1/devices/ [DefaultClientResponse]
Original Stack Trace:
		at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:242) ~[spring-web-5.3.23.jar!/:5.3.23]

**Comment by TheMrBooyah** [comment]
Currently the client is very strongly typed. Therefor it will fail in this case.

You can help out by running this jar file and providing the output:
https://github.com/TheMrBooyah/dirigera-client/releases/download/latest/dirigera-client-dump.jar
`java -jar dirigera-client-dump.jar --dirigera.hostname=<DIRIGERA-IP-ADDRESS>` 
Make sure you created a file `dirigera_access_token` with the access token copied into it.

This way we'll be able to add the speaker as a supported type.

**Comment by littlecake** [comment]
Shore


java -jar ./dirigera-client-dump/target/dirigera-client-dump.jar --dirigera.hostname=192.168.100.27


██████  ██ ██████  ██  ██████  ███████ ██████   █████       ██████ ██      ██ ███████ ███    ██ ████████

██   ██ ██ ██   ██ ██ ██       ██      ██   ██ ██   ██     ██      ██      ██ ██      ████   ██    ██

██   ██ ██ ██████  ██ ██   ███ █████   ██████  ███████     ██      ██      ██ █████   ██ ██  ██    ██

██   ██ ██ ██   ██ ██ ██    ██ ██      ██   ██ ██   ██     ██      ██      ██ ██      ██  ██ ██    ██

██████  ██ ██   ██ ██  ██████  ███████ ██   ██ ██   ██      ██████ ███████ ██ ███████ ██   ████    ██


2022-11-28 00:06:40.822  INFO 1557 --- [           main] d.d.i.d.client.dump.DumpApplication      : Starting DumpApplication v0.0.1-SNAPSHOT using Java 19.0.1 on Michal-Air.localdomain with PID 1557 (/Users/michalkolacek/dump/DirigeraClient-main/dirigera-client-dump/target/dirigera-client-dump.jar started by root in /Users/michalkolacek/dump/DirigeraClient-main)

2022-11-28 00:06:40.824 DEBUG 1557 --- [           main] d.d.i.d.client.dump.DumpApplication      : Running with Spring Boot v2.7.5, Spring v5.3.23

2022-11-28 00:06:40.824  INFO 1557 --- [           main] d.d.i.d.client.dump.DumpApplication      : No active profile set, falling back to 1 default profile: "default"

2022-11-28 00:06:41.124  INFO 1557 --- [           main] d.d.i.d.client.api.http.TokenStore       : Load access token

2022-11-28 00:06:41.402  INFO 1557 --- [           main] d.d.i.d.client.api.http.ClientOAuthApi   : Dirigera client name: Michal-Air.localdomain

2022-11-28 00:06:41.456  INFO 1557 --- [           main] d.d.i.d.client.dump.DumpApplication      : Started DumpApplication in 0.847 seconds (JVM running for 1.233)

{

  "hub" : {

    "id" : "12fa5ddf-bf67-4445-87bf-6ceeedace5af_1",

    "relationId" : "12fa5ddf-bf67-4445-87bf-6ceeedace5af",

    "type" : "gateway",

    "deviceType" : "gateway",

    "createdAt" : "2022-09-14T11:32:34.752Z",

    "isReachable" : true,

    "lastSeen" : "2022-11-27T23:06:00.300Z",

    "attributes" : {

      "customName" : "Kosikarska dirigera",

      "model" : "DIRIGERA Hub for smart products",

      "manufacturer" : "IKEA of Sweden",

      "firmwareVersion" : "2.155.1",

      "hardwareVersion" : "P2.5",

      "serialNumber" : "12fa5ddf-bf67-4445-87bf-6ceeedace5af",

      "identifyStarted" : "2022-11-26T04:11:17.000Z",

      "identifyPeriod" : -1,

      "otaStatus" : "upToDate",

      "otaState" : "readyToCheck",

      "otaProgress" : 0,

      "otaPolicy" : "autoDownload",

      "otaScheduleStart" : "00:00",

      "otaScheduleEnd" : "00:00",

      "permittingJoin" : false,

      "backendConnected" : true,

      "backendConnectionPersistent" : true,

      "backendOnboardingComplete" : true,

      "backendRegion" : "eu-central-1",

      "backendCountryCode" : "CZ",

      "userConsents" : [ {

        "name" : "analytics",

        "value" : "enabled"

      }, {

        "name" : "diagnostics",

        "value" : "enabled"

      } ],

      "logLevel" : 3,

      "coredump" : false,

      "timezone" : "Europe/Prague",

      "countryCode" : "XZ",

      "coordinates" : {

        "latitude" : 49.45936193807304,

        "longitude" : 18.143936907492133,

        "accuracy" : -1

      },

      "isOn" : false

    },

    "capabilities" : {

      "canSend" : [ ],

      "canReceive" : [ "customName", "permittingJoin", "userConsents", "logLevel", "time", "timezone", "countryCode", "coordinates" ]

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ]

  },

  "devices" : [ {

    "id" : "12fa5ddf-bf67-4445-87bf-xxxxx",

    "relationId" : "12fa5ddf-bf67-4445-87bf-xxxx",

    "type" : "gateway",

    "deviceType" : "gateway",

    "createdAt" : "2022-09-14T11:32:34.752Z",

    "isReachable" : true,

    "lastSeen" : "2022-11-27T23:06:00.300Z",

    "attributes" : {

      "customName" : "Kosikarska dirigera",

      "model" : "DIRIGERA Hub for smart products",

      "manufacturer" : "IKEA of Sweden",

      "firmwareVersion" : "2.155.1",

      "hardwareVersion" : "P2.5",

      "serialNumber" : "12fa5ddf-bf67-4445-87bf-xxxx",

      "identifyStarted" : "2022-11-26T04:11:17.000Z",

      "identifyPeriod" : -1,

      "otaStatus" : "upToDate",

      "otaState" : "readyToCheck",

      "otaProgress" : 0,

      "otaPolicy" : "autoDownload",

      "otaScheduleStart" : "00:00",

      "otaScheduleEnd" : "00:00",

      "permittingJoin" : false,

      "backendConnected" : true,

      "backendConnectionPersistent" : true,

      "backendOnboardingComplete" : true,

      "backendRegion" : "eu-central-1",

      "backendCountryCode" : "CZ",

      "userConsents" : [ {

        "name" : "analytics",

        "value" : "enabled"

      }, {

        "name" : "diagnostics",

        "value" : "enabled"

      } ],

      "logLevel" : 3,

      "coredump" : false,

      "timezone" : "Europe/Prague",

      "countryCode" : "XZ",

      "coordinates" : {

        "latitude" : 49.xxxx,

        "longitude" : 18.xxxx,

        "accuracy" : -1

      },

      "isOn" : false

    },

    "capabilities" : {

      "canSend" : [ ],

      "canReceive" : [ "customName", "permittingJoin", "userConsents", "logLevel", "time", "timezone", "countryCode", "coordinates" ]

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ]

  }, {

    "id" : "5038993a-7851-4a89-856c-97ff61ab7c0f_1",

    "type" : "controller",

    "deviceType" : "shortcutController",

    "createdAt" : "2022-11-03T17:00:25.000Z",

    "isReachable" : false,

    "lastSeen" : "2022-11-26T04:11:14.000Z",

    "attributes" : {

      "customName" : "Dobre rano",

      "model" : "TRADFRI SHORTCUT Button",

      "manufacturer" : "IKEA of Sweden",

      "firmwareVersion" : "2.3.080",

      "hardwareVersion" : "1",

      "serialNumber" : "B4E3F9FFFE679FFA",

      "productCode" : "E1812",

      "batteryPercentage" : 74,

      "isOn" : false,

      "lightLevel" : 1,

      "permittingJoin" : false,

      "otaStatus" : "updateAvailable",

      "otaState" : "updateFailed",

      "otaProgress" : 0,

      "otaPolicy" : "autoUpdate",

      "otaScheduleStart" : "00:00",

      "otaScheduleEnd" : "00:00"

    },

    "capabilities" : {

      "canSend" : [ "singlePress", "doublePress", "longPress" ],

      "canReceive" : [ "customName" ]

    },

    "room" : {

      "id" : "f00658cf-6b86-40fe-9f8b-9acda57e6e3d",

      "name" : "Loznice",

      "color" : "ikea_beige_1",

      "icon" : "rooms_arm_chair"

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ],

    "isHidden" : false

  }, {

    "id" : "570b263c-99d7-4f5f-ab27-a39b2639da0c_1",

    "type" : "speaker",

    "deviceType" : "speaker",

    "createdAt" : "2022-11-26T03:11:25.990Z",

    "isReachable" : true,

    "lastSeen" : "2022-11-26T03:11:25.990Z",

    "attributes" : {

      "customName" : "Zahrada Reproduktor",

      "model" : "SYMFONISK Bookshelf S21",

      "manufacturer" : "Sonos, Inc.",

      "firmwareVersion" : "70.3-35220",

      "hardwareVersion" : "1.20.3.3-2.0",

      "serialNumber" : "34-7E-5C-F5-46-A0:6",

      "productCode" : "S21",

      "identifyStarted" : "0001-01-01T00:00:00.000Z",

      "identifyPeriod" : 0,

      "playback" : "playbackIdle",

      "playbackLastChangedTimestamp" : "2022-11-26T03:11:25.990Z",

      "playbackAudio" : { },

      "playbackPosition" : {

        "position" : 0,

        "timestamp" : "2022-11-26T03:11:25.797Z"

      },

      "volume" : 0,

      "isMuted" : true,

      "audioGroup" : "6975a151-910f-404c-93ea-ce54775bfacb"

    },

    "capabilities" : {

      "canSend" : [ ],

      "canReceive" : [ "playback", "playbackAudio", "volume", "isMuted" ]

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ],

    "isHidden" : true

  }, {

    "id" : "a282955d-8d3f-4e9e-a985-848ec68ecba8_1",

    "type" : "light",

    "deviceType" : "light",

    "createdAt" : "2022-11-05T12:00:55.000Z",

    "isReachable" : true,

    "lastSeen" : "2022-11-28T00:02:35.000Z",

    "attributes" : {

      "customName" : "Dvur prava",

      "model" : "TRADFRI bulb E27 W opal 1000lm",

      "manufacturer" : "IKEA of Sweden",

      "firmwareVersion" : "2.3.094",

      "hardwareVersion" : "1",

      "serialNumber" : "000B57FFFEE4588B",

      "productCode" : "LED1622G12E27EU",

      "isOn" : false,

      "startupOnOff" : "startOn",

      "lightLevel" : 100,

      "identifyStarted" : "2000-01-01T00:00:00.000Z",

      "identifyPeriod" : 0,

      "permittingJoin" : false,

      "otaStatus" : "upToDate",

      "otaState" : "readyToCheck",

      "otaProgress" : 0,

      "otaPolicy" : "autoUpdate",

      "otaScheduleStart" : "00:00",

      "otaScheduleEnd" : "00:00"

    },

    "capabilities" : {

      "canSend" : [ ],

      "canReceive" : [ "customName", "isOn", "lightLevel" ]

    },

    "room" : {

      "id" : "1b6ea885-f7a0-4ce1-86ff-a439e4ea02a2",

      "name" : "Dvur",

      "color" : "ikea_beige_1",

      "icon" : "rooms_fence"

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ],

    "isHidden" : false

  }, {

    "id" : "f8a9ebda-2304-4bb0-85b0-66f55224acbd_1",

    "type" : "light",

    "deviceType" : "light",

    "createdAt" : "2022-11-04T18:05:49.000Z",

    "isReachable" : true,

    "lastSeen" : "2022-11-28T00:02:35.000Z",

    "attributes" : {

      "customName" : "Dvur leva",

      "model" : "TRADFRI bulb E27 opal 1000lm",

      "manufacturer" : "IKEA of Sweden",

      "firmwareVersion" : "2.3.094",

      "hardwareVersion" : "1",

      "serialNumber" : "000B57FFFE25A758",

      "productCode" : "LED1623G12",

      "isOn" : false,

      "startupOnOff" : "startOn",

      "lightLevel" : 100,

      "identifyStarted" : "2000-01-01T00:00:00.000Z",

      "identifyPeriod" : 0,

      "permittingJoin" : false,

      "otaStatus" : "upToDate",

      "otaState" : "readyToCheck",

      "otaProgress" : 0,

      "otaPolicy" : "autoUpdate",

      "otaScheduleStart" : "00:00",

      "otaScheduleEnd" : "00:00"

    },

    "capabilities" : {

      "canSend" : [ ],

      "canReceive" : [ "customName", "isOn", "lightLevel" ]

    },

    "room" : {

      "id" : "1b6ea885-f7a0-4ce1-86ff-a439e4ea02a2",

      "name" : "Dvur",

      "color" : "ikea_beige_1",

      "icon" : "rooms_fence"

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ],

    "isHidden" : false

  }, {

    "id" : "2830bc93-4be7-451b-abb1-e25b914e9e32_1",

    "type" : "speaker",

    "deviceType" : "speaker",

    "createdAt" : "2022-11-27T10:08:08.515Z",

    "isReachable" : true,

    "lastSeen" : "2022-11-27T10:08:11.651Z",

    "attributes" : {

      "customName" : "Decak",

      "model" : "SYMFONISK Bookshelf S21",

      "manufacturer" : "Sonos, Inc.",

      "firmwareVersion" : "70.3-35220",

      "hardwareVersion" : "1.20.3.3-2.0",

      "serialNumber" : "34-7E-5C-F5-46-C8:C",

      "productCode" : "S21",

      "identifyStarted" : "0001-01-01T00:00:00.000Z",

      "identifyPeriod" : 0,

      "playback" : "playbackIdle",

      "playbackLastChangedTimestamp" : "2022-11-27T10:08:08.515Z",

      "playbackAudio" : { },

      "playbackPosition" : {

        "position" : 0,

        "timestamp" : "2022-11-27T10:08:08.332Z"

      },

      "volume" : 25,

      "isMuted" : false,

      "audioGroup" : "4a786561-0c2c-4b82-9298-4f775c140d64"

    },

    "capabilities" : {

      "canSend" : [ ],

      "canReceive" : [ "playback", "playbackAudio", "volume", "isMuted" ]

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ],

    "isHidden" : true

  } ],

  "scenes" : [ ],

  "rooms" : [ {

    "id" : "f00658cf-6b86-40fe-9f8b-9acda57e6e3d",

    "name" : "Loznice",

    "color" : "ikea_beige_1",

    "icon" : "rooms_arm_chair"

  }, {

    "id" : "1b6ea885-f7a0-4ce1-86ff-a439e4ea02a2",

    "name" : "Dvur",

    "color" : "ikea_beige_1",

    "icon" : "rooms_fence"

  } ],

  "deviceSets" : [ ],

  "music" : {

    "playlists" : [ ],

    "favorites" : [ ]

  }

}

Michal Kolacek




28. 11. 2022 v 11:27, Remco van Herk ***@***.***>:



Currently the client is very strongly typed. Therefor it will fail in this case.

You can help out by running this jar file and providing the json:
https://github.com/TheMrBooyah/dirigera-client/releases/download/latest/dirigera-client-dump.jar
java -jar dirigera-client-dump.jar --dirigera.hostname=<DIRIGERA-IP-ADDRESS>
Make sure you created a file dirigera_access_token with the access token copied into it.

This way we'll be able to add the speaker as a supported type.

**Comment by TheMrBooyah** [comment]
Thanks! That will help a lot.
Could you also do the same while playing something on the speaker?

**Comment by littlecake** [comment]
Yes
The decak speaker is plaing over airplay
{

    "id" : "2830bc93-4be7-451b-abb1-e25b914e9e32_1",

    "type" : "speaker",

    "deviceType" : "speaker",

    "createdAt" : "2022-11-27T10:08:08.515Z",

    "isReachable" : true,

    "lastSeen" : "2022-11-28T19:52:21.239Z",

    "attributes" : {

      "customName" : "Decak",

      "model" : "SYMFONISK Bookshelf S21",

      "manufacturer" : "Sonos, Inc.",

      "firmwareVersion" : "70.3-35220",

      "hardwareVersion" : "1.20.3.3-2.0",

      "serialNumber" : "34-7E-5C-F5-46-C8:C",

      "productCode" : "S21",

      "identifyStarted" : "0001-01-01T00:00:00.000Z",

      "identifyPeriod" : 0,

      "playback" : "playbackPlaying",

      "playbackLastChangedTimestamp" : "2022-11-28T19:52:18.576Z",

      "playbackAudio" : {

        "serviceType" : "sonos",

        "providerType" : "linein.airplay",

        "playItem" : {

          "title" : "Fml",

          "artist" : "deadmau5",

          "album" : "For Lack of a Better Name",

          "imageURL" : "http://192.168.100.42:1400/getaa?v=0&vli=1&u=3094074005",

          "duration" : 419000

        },

        "nextPlayItem" : {

          "title" : ""

        }

      },

      "playbackPosition" : {

        "position" : 0,

        "timestamp" : "2022-11-28T19:52:18.576Z"

      },

      "volume" : 13,

      "isMuted" : false,

      "audioGroup" : "4a786561-0c2c-4b82-9298-4f775c140d64"

    },

    "capabilities" : {

      "canSend" : [ ],

      "canReceive" : [ "playback", "playbackAudio", "volume", "isMuted" ]

    },

    "deviceSet" : [ ],

    "remoteLinks" : [ ],

    "isHidden" : true

  } ],

  "scenes" : [ ],

  "rooms" : [ {

    "id" : "f00658cf-6b86-40fe-9f8b-9acda57e6e3d",

    "name" : "Loznice",

    "color" : "ikea_beige_1",

    "icon" : "rooms_arm_chair"

  }, {

    "id" : "1b6ea885-f7a0-4ce1-86ff-a439e4ea02a2",

    "name" : "Dvur",

    "color" : "ikea_beige_1",

    "icon" : "rooms_fence"

  } ],

  "deviceSets" : [ ],

  "music" : {

    "playlists" : [ ],

    "favorites" : [ ]

  }

}



Michal Kolacek



28. 11. 2022 v 12:57, Remco van Herk ***@***.***>:



Thanks! That will help a lot.
Could you also do the same while playing something on the speaker?

**Comment by TheMrBooyah** [comment]
Thanks!

**Comment by TheMrBooyah** [comment]
A new update has arrived.

The speaker should now be supported and any unsupported devices shouldn't render the add-on useless (we implemented a default device)
