### ISSUE TITLE
Error 64

### ISSUE THREAD

**Issue by iphoner2804** [TheMrBooyah/hassio-dirigera-client#8]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:648) ~[netty-transport-classes-epoll-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:683) ~[netty-transport-classes-epoll-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:55) ~[netty-transport-classes-epoll-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:522) ~[netty-transport-classes-epoll-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) ~[netty-transport-classes-epoll-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.84.Final.jar!/:4.1.84.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.84.Final.jar!/:4.1.84.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
2023-01-12 20:38:57.264  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Finish event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:38:57.265  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Start event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:38:57.283 ERROR 64 --- [or-http-epoll-3] d.d.i.dirigera.client.api.WebSocketApi   : Error while listening to websocket events: Failed to resolve 'dirigera' after 2 queries 
2023-01-12 20:38:58.284  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Finish event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:38:58.285  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Start event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:38:58.303 ERROR 64 --- [or-http-epoll-3] d.d.i.dirigera.client.api.WebSocketApi   : Error while listening to websocket events: Failed to resolve 'dirigera' after 2 queries 
2023-01-12 20:38:59.305  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Finish event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:38:59.306  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Start event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:38:59.317 ERROR 64 --- [or-http-epoll-3] d.d.i.dirigera.client.api.WebSocketApi   : Error while listening to websocket events: Failed to resolve 'dirigera' after 2 queries 
2023-01-12 20:39:00.319  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Finish event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:39:00.319  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Start event handler thread: id=21, name=boundedElastic-1
2023-01-12 20:39:00.333 ERROR 64 --- [or-http-epoll-3] d.d.i.dirigera.client.api.WebSocketApi   : Error while listening to websocket events: Failed to resolve 'dirigera' after 2 queries 
2023-01-12 20:39:01.335  INFO 64 --- [oundedElastic-1] d.d.i.dirigera.client.api.WebSocketApi   : Finish event handler thread: id=21, name=boundedElastic-1
2023-01-

**Comment by TheMrBooyah** [comment]
What is you addon configuration?
More specifically your hostname?

**Comment by dbgnu76** [comment]
I got the same error with new update  i tryed to reboot several times i even uninstalled whole ikea client and started fresh. But after a power cycle it worked. Don't no why. Now i am testing to see if the bouncing buttons i gone :)
